export const STAGES = [
  { id: 'new', label: 'Ny lead', color: 'bg-accent' },
  { id: 'contacted', label: 'Kontaktad', color: 'bg-warning' },
  { id: 'meeting', label: 'Mote bokat', color: 'bg-[#bf5af2]' },
  { id: 'proposal', label: 'Offert skickad', color: 'bg-[#ff9f0a]' },
  { id: 'customer', label: 'Kund', color: 'bg-success' },
]

export const SOURCES = ['LinkedIn', 'Allabolag', 'Nyheter', 'Referral', 'Annat']

export const SERVICES = [
  'Varumarkesstrategi',
  'Content',
  'Art Direction',
  'Generativ AI',
]

export const demoLeads = [
  {
    id: '1',
    company: 'Flowtech Nordic',
    contact_name: 'Anna Eriksson',
    contact_title: 'Marknadschef',
    email: 'anna.eriksson@flowtech.se',
    phone: '070-123 45 67',
    linkedin_url: 'https://linkedin.com/in/annaeriks',
    source: 'LinkedIn',
    stage: 'new',
    services: ['Varumarkesstrategi', 'Content'],
    score: 85,
    notes: 'Ny marknadschef sedan januari. Soker byrpartner for rebranding.',
    trigger: 'Ny marknadschef',
    created_at: '2026-03-01',
  },
  {
    id: '2',
    company: 'Greenshift AB',
    contact_name: 'Erik Lindberg',
    contact_title: 'VD',
    email: 'erik@greenshift.se',
    phone: '073-987 65 43',
    linkedin_url: 'https://linkedin.com/in/eriklindberg',
    source: 'Nyheter',
    stage: 'contacted',
    services: ['Varumarkesstrategi', 'Art Direction'],
    score: 72,
    notes: 'Fick 15M i finansiering. Planerar varumarkeslansering Q2.',
    trigger: 'Ny finansiering',
    created_at: '2026-02-25',
  },
  {
    id: '3',
    company: 'Solaris Health',
    contact_name: 'Maria Johansson',
    contact_title: 'CMO',
    email: 'maria.johansson@solarishealth.se',
    phone: '076-555 12 34',
    linkedin_url: 'https://linkedin.com/in/mariajoh',
    source: 'LinkedIn',
    stage: 'meeting',
    services: ['Content', 'Generativ AI'],
    score: 91,
    notes: 'Vill utforska AI-driven content. Mote bokat 12 mars.',
    trigger: 'LinkedIn-aktivitet',
    created_at: '2026-02-20',
  },
  {
    id: '4',
    company: 'Berg & Dal Fastigheter',
    contact_name: 'Johan Berg',
    contact_title: 'Marknadsdirektor',
    email: 'johan.berg@bergdal.se',
    phone: '070-222 33 44',
    linkedin_url: 'https://linkedin.com/in/johanberg',
    source: 'Referral',
    stage: 'proposal',
    services: ['Art Direction', 'Varumarkesstrategi'],
    score: 68,
    notes: 'Refererad av Evolan. Behover ny visuell identitet.',
    trigger: 'Referral',
    created_at: '2026-02-15',
  },
  {
    id: '5',
    company: 'Nordic Waves Media',
    contact_name: 'Lisa Strand',
    contact_title: 'Head of Brand',
    email: 'lisa.strand@nordicwaves.se',
    phone: '073-111 22 33',
    linkedin_url: 'https://linkedin.com/in/lisastrand',
    source: 'Allabolag',
    stage: 'new',
    services: ['Generativ AI', 'Content'],
    score: 78,
    notes: 'Snabbvaxande mediebolag. Omsattning +40% senaste aret.',
    trigger: 'Tillvaxt',
    created_at: '2026-03-03',
  },
  {
    id: '6',
    company: 'Pivotal Tech',
    contact_name: 'Oscar Nyman',
    contact_title: 'Marketing Manager',
    email: 'oscar.nyman@pivotaltech.io',
    phone: '076-888 99 00',
    linkedin_url: 'https://linkedin.com/in/oscarnyman',
    source: 'LinkedIn',
    stage: 'contacted',
    services: ['Varumarkesstrategi', 'Generativ AI'],
    score: 80,
    notes: 'Techbolag som vill ga fran B2B till B2C. Behover ny positionering.',
    trigger: 'LinkedIn-aktivitet',
    created_at: '2026-03-04',
  },
]
